[package]

name = "urlencoded"
version = "0.1.0"
authors = ["Patrick Tran <patrick.tran06@gmail.com>",
           "Jonathan Reem <jonathan.reem@gmail.com>",
           "Michael Sproul <micsproul@gmail.com>"]

[lib]

name = "urlencoded"
path = "src/lib.rs"

[dependencies]
iron = "*"
url = "*"
typemap = "*"
plugin = "*"
bodyparser = "*"
